// Mocks generated by Mockito 5.4.4 from annotations
// in movie_app/test/features/movies/data/repos/movies_repos_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:math' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:movie_app/core/errors/failure.dart' as _i6;
import 'package:movie_app/features/movies/data/data_sources/movies_remote_data_sourse.dart'
    as _i3;
import 'package:movie_app/features/movies/data/models/movie_model.dart' as _i2;
import 'package:movie_app/features/movies/data/models/search_model.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMoviesResponseModel_0 extends _i1.SmartFake
    implements _i2.MoviesResponseModel {
  _FakeMoviesResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIterator_1<E> extends _i1.SmartFake implements Iterator<E> {
  _FakeIterator_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieModel_2 extends _i1.SmartFake implements _i2.MovieModel {
  _FakeMovieModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MoviesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesRemoteDataSource extends _i1.Mock
    implements _i3.MoviesRemoteDataSource {
  @override
  _i4.Future<_i2.MoviesResponseModel> fetchMovies({int? pageNumber = 0}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMovies,
          [],
          {#pageNumber: pageNumber},
        ),
        returnValue: _i4.Future<_i2.MoviesResponseModel>.value(
            _FakeMoviesResponseModel_0(
          this,
          Invocation.method(
            #fetchMovies,
            [],
            {#pageNumber: pageNumber},
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.MoviesResponseModel>.value(
            _FakeMoviesResponseModel_0(
          this,
          Invocation.method(
            #fetchMovies,
            [],
            {#pageNumber: pageNumber},
          ),
        )),
      ) as _i4.Future<_i2.MoviesResponseModel>);

  @override
  _i4.Future<_i2.MoviesResponseModel> fetchSearchMovies(
          {required _i5.SearchModel? searchModel}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSearchMovies,
          [],
          {#searchModel: searchModel},
        ),
        returnValue: _i4.Future<_i2.MoviesResponseModel>.value(
            _FakeMoviesResponseModel_0(
          this,
          Invocation.method(
            #fetchSearchMovies,
            [],
            {#searchModel: searchModel},
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.MoviesResponseModel>.value(
            _FakeMoviesResponseModel_0(
          this,
          Invocation.method(
            #fetchSearchMovies,
            [],
            {#searchModel: searchModel},
          ),
        )),
      ) as _i4.Future<_i2.MoviesResponseModel>);
}

/// A class which mocks [ServerFailure].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerFailure extends _i1.Mock implements _i6.ServerFailure {
  @override
  String get message => (super.noSuchMethod(
        Invocation.getter(#message),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.getter(#message),
        ),
      ) as String);
}

/// A class which mocks [List].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesList extends _i1.Mock implements List<_i2.MovieModel> {
  @override
  set first(_i2.MovieModel? value) => super.noSuchMethod(
        Invocation.setter(
          #first,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set last(_i2.MovieModel? value) => super.noSuchMethod(
        Invocation.setter(
          #last,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set length(int? newLength) => super.noSuchMethod(
        Invocation.setter(
          #length,
          newLength,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Iterable<_i2.MovieModel> get reversed => (super.noSuchMethod(
        Invocation.getter(#reversed),
        returnValue: <_i2.MovieModel>[],
        returnValueForMissingStub: <_i2.MovieModel>[],
      ) as Iterable<_i2.MovieModel>);

  @override
  Iterator<_i2.MovieModel> get iterator => (super.noSuchMethod(
        Invocation.getter(#iterator),
        returnValue: _FakeIterator_1<_i2.MovieModel>(
          this,
          Invocation.getter(#iterator),
        ),
        returnValueForMissingStub: _FakeIterator_1<_i2.MovieModel>(
          this,
          Invocation.getter(#iterator),
        ),
      ) as Iterator<_i2.MovieModel>);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.MovieModel get first => (super.noSuchMethod(
        Invocation.getter(#first),
        returnValue: _FakeMovieModel_2(
          this,
          Invocation.getter(#first),
        ),
        returnValueForMissingStub: _FakeMovieModel_2(
          this,
          Invocation.getter(#first),
        ),
      ) as _i2.MovieModel);

  @override
  _i2.MovieModel get last => (super.noSuchMethod(
        Invocation.getter(#last),
        returnValue: _FakeMovieModel_2(
          this,
          Invocation.getter(#last),
        ),
        returnValueForMissingStub: _FakeMovieModel_2(
          this,
          Invocation.getter(#last),
        ),
      ) as _i2.MovieModel);

  @override
  _i2.MovieModel get single => (super.noSuchMethod(
        Invocation.getter(#single),
        returnValue: _FakeMovieModel_2(
          this,
          Invocation.getter(#single),
        ),
        returnValueForMissingStub: _FakeMovieModel_2(
          this,
          Invocation.getter(#single),
        ),
      ) as _i2.MovieModel);

  @override
  List<R> cast<R>() => (super.noSuchMethod(
        Invocation.method(
          #cast,
          [],
        ),
        returnValue: <R>[],
        returnValueForMissingStub: <R>[],
      ) as List<R>);

  @override
  _i2.MovieModel operator [](int? index) => (super.noSuchMethod(
        Invocation.method(
          #[],
          [index],
        ),
        returnValue: _FakeMovieModel_2(
          this,
          Invocation.method(
            #[],
            [index],
          ),
        ),
        returnValueForMissingStub: _FakeMovieModel_2(
          this,
          Invocation.method(
            #[],
            [index],
          ),
        ),
      ) as _i2.MovieModel);

  @override
  void operator []=(
    int? index,
    _i2.MovieModel? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #[]=,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i2.MovieModel? value) => super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addAll(Iterable<_i2.MovieModel>? iterable) => super.noSuchMethod(
        Invocation.method(
          #addAll,
          [iterable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sort(
          [int Function(
            _i2.MovieModel,
            _i2.MovieModel,
          )? compare]) =>
      super.noSuchMethod(
        Invocation.method(
          #sort,
          [compare],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void shuffle([_i8.Random? random]) => super.noSuchMethod(
        Invocation.method(
          #shuffle,
          [random],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int indexOf(
    _i2.MovieModel? element, [
    int? start = 0,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexOf,
          [
            element,
            start,
          ],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int indexWhere(
    bool Function(_i2.MovieModel)? test, [
    int? start = 0,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexWhere,
          [
            test,
            start,
          ],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int lastIndexWhere(
    bool Function(_i2.MovieModel)? test, [
    int? start,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastIndexWhere,
          [
            test,
            start,
          ],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int lastIndexOf(
    _i2.MovieModel? element, [
    int? start,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastIndexOf,
          [
            element,
            start,
          ],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void insert(
    int? index,
    _i2.MovieModel? element,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            index,
            element,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void insertAll(
    int? index,
    Iterable<_i2.MovieModel>? iterable,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #insertAll,
          [
            index,
            iterable,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAll(
    int? index,
    Iterable<_i2.MovieModel>? iterable,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAll,
          [
            index,
            iterable,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool remove(Object? value) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [value],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.MovieModel removeAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeAt,
          [index],
        ),
        returnValue: _FakeMovieModel_2(
          this,
          Invocation.method(
            #removeAt,
            [index],
          ),
        ),
        returnValueForMissingStub: _FakeMovieModel_2(
          this,
          Invocation.method(
            #removeAt,
            [index],
          ),
        ),
      ) as _i2.MovieModel);

  @override
  _i2.MovieModel removeLast() => (super.noSuchMethod(
        Invocation.method(
          #removeLast,
          [],
        ),
        returnValue: _FakeMovieModel_2(
          this,
          Invocation.method(
            #removeLast,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeMovieModel_2(
          this,
          Invocation.method(
            #removeLast,
            [],
          ),
        ),
      ) as _i2.MovieModel);

  @override
  void removeWhere(bool Function(_i2.MovieModel)? test) => super.noSuchMethod(
        Invocation.method(
          #removeWhere,
          [test],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void retainWhere(bool Function(_i2.MovieModel)? test) => super.noSuchMethod(
        Invocation.method(
          #retainWhere,
          [test],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i2.MovieModel> operator +(List<_i2.MovieModel>? other) =>
      (super.noSuchMethod(
        Invocation.method(
          #+,
          [other],
        ),
        returnValue: <_i2.MovieModel>[],
        returnValueForMissingStub: <_i2.MovieModel>[],
      ) as List<_i2.MovieModel>);

  @override
  List<_i2.MovieModel> sublist(
    int? start, [
    int? end,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #sublist,
          [
            start,
            end,
          ],
        ),
        returnValue: <_i2.MovieModel>[],
        returnValueForMissingStub: <_i2.MovieModel>[],
      ) as List<_i2.MovieModel>);

  @override
  Iterable<_i2.MovieModel> getRange(
    int? start,
    int? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRange,
          [
            start,
            end,
          ],
        ),
        returnValue: <_i2.MovieModel>[],
        returnValueForMissingStub: <_i2.MovieModel>[],
      ) as Iterable<_i2.MovieModel>);

  @override
  void setRange(
    int? start,
    int? end,
    Iterable<_i2.MovieModel>? iterable, [
    int? skipCount = 0,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #setRange,
          [
            start,
            end,
            iterable,
            skipCount,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeRange(
    int? start,
    int? end,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeRange,
          [
            start,
            end,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fillRange(
    int? start,
    int? end, [
    _i2.MovieModel? fillValue,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #fillRange,
          [
            start,
            end,
            fillValue,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void replaceRange(
    int? start,
    int? end,
    Iterable<_i2.MovieModel>? replacements,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #replaceRange,
          [
            start,
            end,
            replacements,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<int, _i2.MovieModel> asMap() => (super.noSuchMethod(
        Invocation.method(
          #asMap,
          [],
        ),
        returnValue: <int, _i2.MovieModel>{},
        returnValueForMissingStub: <int, _i2.MovieModel>{},
      ) as Map<int, _i2.MovieModel>);

  @override
  Iterable<_i2.MovieModel> followedBy(Iterable<_i2.MovieModel>? other) =>
      (super.noSuchMethod(
        Invocation.method(
          #followedBy,
          [other],
        ),
        returnValue: <_i2.MovieModel>[],
        returnValueForMissingStub: <_i2.MovieModel>[],
      ) as Iterable<_i2.MovieModel>);

  @override
  Iterable<T> map<T>(T Function(_i2.MovieModel)? toElement) =>
      (super.noSuchMethod(
        Invocation.method(
          #map,
          [toElement],
        ),
        returnValue: <T>[],
        returnValueForMissingStub: <T>[],
      ) as Iterable<T>);

  @override
  Iterable<_i2.MovieModel> where(bool Function(_i2.MovieModel)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #where,
          [test],
        ),
        returnValue: <_i2.MovieModel>[],
        returnValueForMissingStub: <_i2.MovieModel>[],
      ) as Iterable<_i2.MovieModel>);

  @override
  Iterable<T> whereType<T>() => (super.noSuchMethod(
        Invocation.method(
          #whereType,
          [],
        ),
        returnValue: <T>[],
        returnValueForMissingStub: <T>[],
      ) as Iterable<T>);

  @override
  Iterable<T> expand<T>(Iterable<T> Function(_i2.MovieModel)? toElements) =>
      (super.noSuchMethod(
        Invocation.method(
          #expand,
          [toElements],
        ),
        returnValue: <T>[],
        returnValueForMissingStub: <T>[],
      ) as Iterable<T>);

  @override
  bool contains(Object? element) => (super.noSuchMethod(
        Invocation.method(
          #contains,
          [element],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void forEach(void Function(_i2.MovieModel)? action) => super.noSuchMethod(
        Invocation.method(
          #forEach,
          [action],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.MovieModel reduce(
          _i2.MovieModel Function(
            _i2.MovieModel,
            _i2.MovieModel,
          )? combine) =>
      (super.noSuchMethod(
        Invocation.method(
          #reduce,
          [combine],
        ),
        returnValue: _FakeMovieModel_2(
          this,
          Invocation.method(
            #reduce,
            [combine],
          ),
        ),
        returnValueForMissingStub: _FakeMovieModel_2(
          this,
          Invocation.method(
            #reduce,
            [combine],
          ),
        ),
      ) as _i2.MovieModel);

  @override
  T fold<T>(
    T? initialValue,
    T Function(
      T,
      _i2.MovieModel,
    )? combine,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fold,
          [
            initialValue,
            combine,
          ],
        ),
        returnValue: _i7.dummyValue<T>(
          this,
          Invocation.method(
            #fold,
            [
              initialValue,
              combine,
            ],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<T>(
          this,
          Invocation.method(
            #fold,
            [
              initialValue,
              combine,
            ],
          ),
        ),
      ) as T);

  @override
  bool every(bool Function(_i2.MovieModel)? test) => (super.noSuchMethod(
        Invocation.method(
          #every,
          [test],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String join([String? separator = r'']) => (super.noSuchMethod(
        Invocation.method(
          #join,
          [separator],
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #join,
            [separator],
          ),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #join,
            [separator],
          ),
        ),
      ) as String);

  @override
  bool any(bool Function(_i2.MovieModel)? test) => (super.noSuchMethod(
        Invocation.method(
          #any,
          [test],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i2.MovieModel> toList({bool? growable = true}) => (super.noSuchMethod(
        Invocation.method(
          #toList,
          [],
          {#growable: growable},
        ),
        returnValue: <_i2.MovieModel>[],
        returnValueForMissingStub: <_i2.MovieModel>[],
      ) as List<_i2.MovieModel>);

  @override
  Set<_i2.MovieModel> toSet() => (super.noSuchMethod(
        Invocation.method(
          #toSet,
          [],
        ),
        returnValue: <_i2.MovieModel>{},
        returnValueForMissingStub: <_i2.MovieModel>{},
      ) as Set<_i2.MovieModel>);

  @override
  Iterable<_i2.MovieModel> take(int? count) => (super.noSuchMethod(
        Invocation.method(
          #take,
          [count],
        ),
        returnValue: <_i2.MovieModel>[],
        returnValueForMissingStub: <_i2.MovieModel>[],
      ) as Iterable<_i2.MovieModel>);

  @override
  Iterable<_i2.MovieModel> takeWhile(bool Function(_i2.MovieModel)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #takeWhile,
          [test],
        ),
        returnValue: <_i2.MovieModel>[],
        returnValueForMissingStub: <_i2.MovieModel>[],
      ) as Iterable<_i2.MovieModel>);

  @override
  Iterable<_i2.MovieModel> skip(int? count) => (super.noSuchMethod(
        Invocation.method(
          #skip,
          [count],
        ),
        returnValue: <_i2.MovieModel>[],
        returnValueForMissingStub: <_i2.MovieModel>[],
      ) as Iterable<_i2.MovieModel>);

  @override
  Iterable<_i2.MovieModel> skipWhile(bool Function(_i2.MovieModel)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #skipWhile,
          [test],
        ),
        returnValue: <_i2.MovieModel>[],
        returnValueForMissingStub: <_i2.MovieModel>[],
      ) as Iterable<_i2.MovieModel>);

  @override
  _i2.MovieModel firstWhere(
    bool Function(_i2.MovieModel)? test, {
    _i2.MovieModel Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #firstWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _FakeMovieModel_2(
          this,
          Invocation.method(
            #firstWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
        returnValueForMissingStub: _FakeMovieModel_2(
          this,
          Invocation.method(
            #firstWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
      ) as _i2.MovieModel);

  @override
  _i2.MovieModel lastWhere(
    bool Function(_i2.MovieModel)? test, {
    _i2.MovieModel Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _FakeMovieModel_2(
          this,
          Invocation.method(
            #lastWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
        returnValueForMissingStub: _FakeMovieModel_2(
          this,
          Invocation.method(
            #lastWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
      ) as _i2.MovieModel);

  @override
  _i2.MovieModel singleWhere(
    bool Function(_i2.MovieModel)? test, {
    _i2.MovieModel Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #singleWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _FakeMovieModel_2(
          this,
          Invocation.method(
            #singleWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
        returnValueForMissingStub: _FakeMovieModel_2(
          this,
          Invocation.method(
            #singleWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
      ) as _i2.MovieModel);

  @override
  _i2.MovieModel elementAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #elementAt,
          [index],
        ),
        returnValue: _FakeMovieModel_2(
          this,
          Invocation.method(
            #elementAt,
            [index],
          ),
        ),
        returnValueForMissingStub: _FakeMovieModel_2(
          this,
          Invocation.method(
            #elementAt,
            [index],
          ),
        ),
      ) as _i2.MovieModel);
}

/// A class which mocks [SearchModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchModel extends _i1.Mock implements _i5.SearchModel {
  @override
  int get pageNumber => (super.noSuchMethod(
        Invocation.getter(#pageNumber),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  String get textSearch => (super.noSuchMethod(
        Invocation.getter(#textSearch),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#textSearch),
        ),
        returnValueForMissingStub: _i7.dummyValue<String>(
          this,
          Invocation.getter(#textSearch),
        ),
      ) as String);
}
