// Mocks generated by Mockito 5.4.4 from annotations
// in movie_app/test/features/movies/presentation/cubit/movies_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:math' as _i10;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:movie_app/core/errors/failure.dart' as _i7;
import 'package:movie_app/features/movies/data/models/search_model.dart' as _i9;
import 'package:movie_app/features/movies/domain/entities/movie_entity.dart'
    as _i4;
import 'package:movie_app/features/movies/domain/repositories/movies_repo.dart'
    as _i2;
import 'package:movie_app/features/movies/domain/use_cases/fetch_movies_use_case.dart'
    as _i5;
import 'package:movie_app/features/movies/domain/use_cases/fetch_result_search_movies_use_case.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMoviesRepo_0 extends _i1.SmartFake implements _i2.MoviesRepo {
  _FakeMoviesRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIterator_2<E> extends _i1.SmartFake implements Iterator<E> {
  _FakeIterator_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieEntity_3 extends _i1.SmartFake implements _i4.MovieEntity {
  _FakeMovieEntity_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchMoviesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchMoviesUseCase extends _i1.Mock
    implements _i5.FetchMoviesUseCase {
  @override
  _i2.MoviesRepo get moviesRepo => (super.noSuchMethod(
        Invocation.getter(#moviesRepo),
        returnValue: _FakeMoviesRepo_0(
          this,
          Invocation.getter(#moviesRepo),
        ),
        returnValueForMissingStub: _FakeMoviesRepo_0(
          this,
          Invocation.getter(#moviesRepo),
        ),
      ) as _i2.MoviesRepo);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i4.MovieEntity>>> call(
          [int? param = 0]) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [param],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, List<_i4.MovieEntity>>>.value(
                _FakeEither_1<_i7.Failure, List<_i4.MovieEntity>>(
          this,
          Invocation.method(
            #call,
            [param],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Either<_i7.Failure, List<_i4.MovieEntity>>>.value(
                _FakeEither_1<_i7.Failure, List<_i4.MovieEntity>>(
          this,
          Invocation.method(
            #call,
            [param],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i4.MovieEntity>>>);
}

/// A class which mocks [FetchResultSearchMoviesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchResultSearchMoviesUseCase extends _i1.Mock
    implements _i8.FetchResultSearchMoviesUseCase {
  @override
  _i2.MoviesRepo get moviesRepo => (super.noSuchMethod(
        Invocation.getter(#moviesRepo),
        returnValue: _FakeMoviesRepo_0(
          this,
          Invocation.getter(#moviesRepo),
        ),
        returnValueForMissingStub: _FakeMoviesRepo_0(
          this,
          Invocation.getter(#moviesRepo),
        ),
      ) as _i2.MoviesRepo);

  @override
  _i6.Future<_i3.Either<_i7.Failure, List<_i4.MovieEntity>>> call(
          [_i9.SearchModel? param]) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [param],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, List<_i4.MovieEntity>>>.value(
                _FakeEither_1<_i7.Failure, List<_i4.MovieEntity>>(
          this,
          Invocation.method(
            #call,
            [param],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.Either<_i7.Failure, List<_i4.MovieEntity>>>.value(
                _FakeEither_1<_i7.Failure, List<_i4.MovieEntity>>(
          this,
          Invocation.method(
            #call,
            [param],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, List<_i4.MovieEntity>>>);
}

/// A class which mocks [List].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieList extends _i1.Mock implements List<_i4.MovieEntity> {
  @override
  set first(_i4.MovieEntity? value) => super.noSuchMethod(
        Invocation.setter(
          #first,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set last(_i4.MovieEntity? value) => super.noSuchMethod(
        Invocation.setter(
          #last,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  set length(int? newLength) => super.noSuchMethod(
        Invocation.setter(
          #length,
          newLength,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Iterable<_i4.MovieEntity> get reversed => (super.noSuchMethod(
        Invocation.getter(#reversed),
        returnValue: <_i4.MovieEntity>[],
        returnValueForMissingStub: <_i4.MovieEntity>[],
      ) as Iterable<_i4.MovieEntity>);

  @override
  Iterator<_i4.MovieEntity> get iterator => (super.noSuchMethod(
        Invocation.getter(#iterator),
        returnValue: _FakeIterator_2<_i4.MovieEntity>(
          this,
          Invocation.getter(#iterator),
        ),
        returnValueForMissingStub: _FakeIterator_2<_i4.MovieEntity>(
          this,
          Invocation.getter(#iterator),
        ),
      ) as Iterator<_i4.MovieEntity>);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.MovieEntity get first => (super.noSuchMethod(
        Invocation.getter(#first),
        returnValue: _FakeMovieEntity_3(
          this,
          Invocation.getter(#first),
        ),
        returnValueForMissingStub: _FakeMovieEntity_3(
          this,
          Invocation.getter(#first),
        ),
      ) as _i4.MovieEntity);

  @override
  _i4.MovieEntity get last => (super.noSuchMethod(
        Invocation.getter(#last),
        returnValue: _FakeMovieEntity_3(
          this,
          Invocation.getter(#last),
        ),
        returnValueForMissingStub: _FakeMovieEntity_3(
          this,
          Invocation.getter(#last),
        ),
      ) as _i4.MovieEntity);

  @override
  _i4.MovieEntity get single => (super.noSuchMethod(
        Invocation.getter(#single),
        returnValue: _FakeMovieEntity_3(
          this,
          Invocation.getter(#single),
        ),
        returnValueForMissingStub: _FakeMovieEntity_3(
          this,
          Invocation.getter(#single),
        ),
      ) as _i4.MovieEntity);

  @override
  List<R> cast<R>() => (super.noSuchMethod(
        Invocation.method(
          #cast,
          [],
        ),
        returnValue: <R>[],
        returnValueForMissingStub: <R>[],
      ) as List<R>);

  @override
  _i4.MovieEntity operator [](int? index) => (super.noSuchMethod(
        Invocation.method(
          #[],
          [index],
        ),
        returnValue: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #[],
            [index],
          ),
        ),
        returnValueForMissingStub: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #[],
            [index],
          ),
        ),
      ) as _i4.MovieEntity);

  @override
  void operator []=(
    int? index,
    _i4.MovieEntity? value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #[]=,
          [
            index,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void add(_i4.MovieEntity? value) => super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addAll(Iterable<_i4.MovieEntity>? iterable) => super.noSuchMethod(
        Invocation.method(
          #addAll,
          [iterable],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sort(
          [int Function(
            _i4.MovieEntity,
            _i4.MovieEntity,
          )? compare]) =>
      super.noSuchMethod(
        Invocation.method(
          #sort,
          [compare],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void shuffle([_i10.Random? random]) => super.noSuchMethod(
        Invocation.method(
          #shuffle,
          [random],
        ),
        returnValueForMissingStub: null,
      );

  @override
  int indexOf(
    _i4.MovieEntity? element, [
    int? start = 0,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexOf,
          [
            element,
            start,
          ],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int indexWhere(
    bool Function(_i4.MovieEntity)? test, [
    int? start = 0,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexWhere,
          [
            test,
            start,
          ],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int lastIndexWhere(
    bool Function(_i4.MovieEntity)? test, [
    int? start,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastIndexWhere,
          [
            test,
            start,
          ],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  int lastIndexOf(
    _i4.MovieEntity? element, [
    int? start,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastIndexOf,
          [
            element,
            start,
          ],
        ),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void insert(
    int? index,
    _i4.MovieEntity? element,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            index,
            element,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void insertAll(
    int? index,
    Iterable<_i4.MovieEntity>? iterable,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #insertAll,
          [
            index,
            iterable,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAll(
    int? index,
    Iterable<_i4.MovieEntity>? iterable,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setAll,
          [
            index,
            iterable,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool remove(Object? value) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [value],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.MovieEntity removeAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #removeAt,
          [index],
        ),
        returnValue: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #removeAt,
            [index],
          ),
        ),
        returnValueForMissingStub: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #removeAt,
            [index],
          ),
        ),
      ) as _i4.MovieEntity);

  @override
  _i4.MovieEntity removeLast() => (super.noSuchMethod(
        Invocation.method(
          #removeLast,
          [],
        ),
        returnValue: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #removeLast,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #removeLast,
            [],
          ),
        ),
      ) as _i4.MovieEntity);

  @override
  void removeWhere(bool Function(_i4.MovieEntity)? test) => super.noSuchMethod(
        Invocation.method(
          #removeWhere,
          [test],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void retainWhere(bool Function(_i4.MovieEntity)? test) => super.noSuchMethod(
        Invocation.method(
          #retainWhere,
          [test],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i4.MovieEntity> operator +(List<_i4.MovieEntity>? other) =>
      (super.noSuchMethod(
        Invocation.method(
          #+,
          [other],
        ),
        returnValue: <_i4.MovieEntity>[],
        returnValueForMissingStub: <_i4.MovieEntity>[],
      ) as List<_i4.MovieEntity>);

  @override
  List<_i4.MovieEntity> sublist(
    int? start, [
    int? end,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #sublist,
          [
            start,
            end,
          ],
        ),
        returnValue: <_i4.MovieEntity>[],
        returnValueForMissingStub: <_i4.MovieEntity>[],
      ) as List<_i4.MovieEntity>);

  @override
  Iterable<_i4.MovieEntity> getRange(
    int? start,
    int? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRange,
          [
            start,
            end,
          ],
        ),
        returnValue: <_i4.MovieEntity>[],
        returnValueForMissingStub: <_i4.MovieEntity>[],
      ) as Iterable<_i4.MovieEntity>);

  @override
  void setRange(
    int? start,
    int? end,
    Iterable<_i4.MovieEntity>? iterable, [
    int? skipCount = 0,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #setRange,
          [
            start,
            end,
            iterable,
            skipCount,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeRange(
    int? start,
    int? end,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeRange,
          [
            start,
            end,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void fillRange(
    int? start,
    int? end, [
    _i4.MovieEntity? fillValue,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #fillRange,
          [
            start,
            end,
            fillValue,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void replaceRange(
    int? start,
    int? end,
    Iterable<_i4.MovieEntity>? replacements,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #replaceRange,
          [
            start,
            end,
            replacements,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<int, _i4.MovieEntity> asMap() => (super.noSuchMethod(
        Invocation.method(
          #asMap,
          [],
        ),
        returnValue: <int, _i4.MovieEntity>{},
        returnValueForMissingStub: <int, _i4.MovieEntity>{},
      ) as Map<int, _i4.MovieEntity>);

  @override
  Iterable<_i4.MovieEntity> followedBy(Iterable<_i4.MovieEntity>? other) =>
      (super.noSuchMethod(
        Invocation.method(
          #followedBy,
          [other],
        ),
        returnValue: <_i4.MovieEntity>[],
        returnValueForMissingStub: <_i4.MovieEntity>[],
      ) as Iterable<_i4.MovieEntity>);

  @override
  Iterable<T> map<T>(T Function(_i4.MovieEntity)? toElement) =>
      (super.noSuchMethod(
        Invocation.method(
          #map,
          [toElement],
        ),
        returnValue: <T>[],
        returnValueForMissingStub: <T>[],
      ) as Iterable<T>);

  @override
  Iterable<_i4.MovieEntity> where(bool Function(_i4.MovieEntity)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #where,
          [test],
        ),
        returnValue: <_i4.MovieEntity>[],
        returnValueForMissingStub: <_i4.MovieEntity>[],
      ) as Iterable<_i4.MovieEntity>);

  @override
  Iterable<T> whereType<T>() => (super.noSuchMethod(
        Invocation.method(
          #whereType,
          [],
        ),
        returnValue: <T>[],
        returnValueForMissingStub: <T>[],
      ) as Iterable<T>);

  @override
  Iterable<T> expand<T>(Iterable<T> Function(_i4.MovieEntity)? toElements) =>
      (super.noSuchMethod(
        Invocation.method(
          #expand,
          [toElements],
        ),
        returnValue: <T>[],
        returnValueForMissingStub: <T>[],
      ) as Iterable<T>);

  @override
  bool contains(Object? element) => (super.noSuchMethod(
        Invocation.method(
          #contains,
          [element],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void forEach(void Function(_i4.MovieEntity)? action) => super.noSuchMethod(
        Invocation.method(
          #forEach,
          [action],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.MovieEntity reduce(
          _i4.MovieEntity Function(
            _i4.MovieEntity,
            _i4.MovieEntity,
          )? combine) =>
      (super.noSuchMethod(
        Invocation.method(
          #reduce,
          [combine],
        ),
        returnValue: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #reduce,
            [combine],
          ),
        ),
        returnValueForMissingStub: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #reduce,
            [combine],
          ),
        ),
      ) as _i4.MovieEntity);

  @override
  T fold<T>(
    T? initialValue,
    T Function(
      T,
      _i4.MovieEntity,
    )? combine,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fold,
          [
            initialValue,
            combine,
          ],
        ),
        returnValue: _i11.dummyValue<T>(
          this,
          Invocation.method(
            #fold,
            [
              initialValue,
              combine,
            ],
          ),
        ),
        returnValueForMissingStub: _i11.dummyValue<T>(
          this,
          Invocation.method(
            #fold,
            [
              initialValue,
              combine,
            ],
          ),
        ),
      ) as T);

  @override
  bool every(bool Function(_i4.MovieEntity)? test) => (super.noSuchMethod(
        Invocation.method(
          #every,
          [test],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String join([String? separator = r'']) => (super.noSuchMethod(
        Invocation.method(
          #join,
          [separator],
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #join,
            [separator],
          ),
        ),
        returnValueForMissingStub: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #join,
            [separator],
          ),
        ),
      ) as String);

  @override
  bool any(bool Function(_i4.MovieEntity)? test) => (super.noSuchMethod(
        Invocation.method(
          #any,
          [test],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<_i4.MovieEntity> toList({bool? growable = true}) => (super.noSuchMethod(
        Invocation.method(
          #toList,
          [],
          {#growable: growable},
        ),
        returnValue: <_i4.MovieEntity>[],
        returnValueForMissingStub: <_i4.MovieEntity>[],
      ) as List<_i4.MovieEntity>);

  @override
  Set<_i4.MovieEntity> toSet() => (super.noSuchMethod(
        Invocation.method(
          #toSet,
          [],
        ),
        returnValue: <_i4.MovieEntity>{},
        returnValueForMissingStub: <_i4.MovieEntity>{},
      ) as Set<_i4.MovieEntity>);

  @override
  Iterable<_i4.MovieEntity> take(int? count) => (super.noSuchMethod(
        Invocation.method(
          #take,
          [count],
        ),
        returnValue: <_i4.MovieEntity>[],
        returnValueForMissingStub: <_i4.MovieEntity>[],
      ) as Iterable<_i4.MovieEntity>);

  @override
  Iterable<_i4.MovieEntity> takeWhile(bool Function(_i4.MovieEntity)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #takeWhile,
          [test],
        ),
        returnValue: <_i4.MovieEntity>[],
        returnValueForMissingStub: <_i4.MovieEntity>[],
      ) as Iterable<_i4.MovieEntity>);

  @override
  Iterable<_i4.MovieEntity> skip(int? count) => (super.noSuchMethod(
        Invocation.method(
          #skip,
          [count],
        ),
        returnValue: <_i4.MovieEntity>[],
        returnValueForMissingStub: <_i4.MovieEntity>[],
      ) as Iterable<_i4.MovieEntity>);

  @override
  Iterable<_i4.MovieEntity> skipWhile(bool Function(_i4.MovieEntity)? test) =>
      (super.noSuchMethod(
        Invocation.method(
          #skipWhile,
          [test],
        ),
        returnValue: <_i4.MovieEntity>[],
        returnValueForMissingStub: <_i4.MovieEntity>[],
      ) as Iterable<_i4.MovieEntity>);

  @override
  _i4.MovieEntity firstWhere(
    bool Function(_i4.MovieEntity)? test, {
    _i4.MovieEntity Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #firstWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #firstWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
        returnValueForMissingStub: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #firstWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
      ) as _i4.MovieEntity);

  @override
  _i4.MovieEntity lastWhere(
    bool Function(_i4.MovieEntity)? test, {
    _i4.MovieEntity Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #lastWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #lastWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
        returnValueForMissingStub: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #lastWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
      ) as _i4.MovieEntity);

  @override
  _i4.MovieEntity singleWhere(
    bool Function(_i4.MovieEntity)? test, {
    _i4.MovieEntity Function()? orElse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #singleWhere,
          [test],
          {#orElse: orElse},
        ),
        returnValue: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #singleWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
        returnValueForMissingStub: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #singleWhere,
            [test],
            {#orElse: orElse},
          ),
        ),
      ) as _i4.MovieEntity);

  @override
  _i4.MovieEntity elementAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #elementAt,
          [index],
        ),
        returnValue: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #elementAt,
            [index],
          ),
        ),
        returnValueForMissingStub: _FakeMovieEntity_3(
          this,
          Invocation.method(
            #elementAt,
            [index],
          ),
        ),
      ) as _i4.MovieEntity);
}
